# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Trademindx - Artificial Intelligence for Cryptocurrency Trading
tagline: Get the edge in cryptocurrency trading!
description: >- # this means to ignore newlines until "baseurl:"
  Artificial intelligence to analyze cryptocurrency market sentiment and help maximize your returns.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://trademindx.com" # the base hostname & protocol for your site, e.g. http://example.com
production_url : http://trademindx.github.io.com/blog
BASE_PATH : http://trademindx.com/blog
homepage: https://trademindx.com
twitter_username: trademindx
github_username:  trademindx
google_analytics: "UA-112080053-1"
comments: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
